const country_list = ["US", "FR", "AUS", "GER", "CAN", "UK"];
const platform_list = [
    "Woo Commerce",
    "Magento",
    "Shopify Plus",
    "Custom",
    "Shopify",
    "BigCommerce",
];
const revenue_list = ["0-10000", "10000-20000"];
const tech_list = ["Google", "Gmail", "Cloudtail", "Microsoft"];
const industry_list = [
    "environmental services",
    "fund-raising",
    "agriculture",
    "mechanical or industrial engineering",
    "animation",
    "hospital & health care",
    "think tanks",
    "writing & editing",
    "research",
    "libraries",
    "defense & space",
    "higher education",
    "facilities services",
    "management consulting",
    "apparel & fashion",
    "electrical/electronic manufacturing",
    "construction",
    "graphic design",
    "wine & spirits",
    "printing",
    "international trade & development",
    "recreational facilities & services",
    "oil & energy",
    "information technology & services",
    "marketing & advertising",
    "veterinary",
    "insurance",
    "restaurants",
    "events services",
    "real estate",
    "transportation/trucking/railroad",
    "professional training & coaching",
    "glass, ceramics & concrete",
    "financial services",
    "design",
    "public safety",
    "computer hardware",
    "food & beverages",
    "medical devices",
    "primary/secondary education",
    "mental health care",
    "alternative medicine",
    "luxury goods & jewelry",
    "architecture & planning",
    "pharmaceuticals",
    "chemicals",
    "health, wellness & fitness",
    "machinery",
    "education management",
    "wholesale",
    "consumer electronics",
    "mining & metals",
    "sporting goods",
    "hospitality",
    "fishery",
    "farming",
    "packaging & containers",
    "textiles",
    "furniture",
    "photography",
    "tobacco",
    "cosmetics",
    "semiconductors",
    "airlines/aviation",
    "computer & network security",
    "medical practice",
    "consumer goods",
    "business supplies & equipment",
    "human resources",
    "food production",
    "ranching",
    "renewables & environment",
    "import & export",
    "e-learning",
    "online media",
    "retail",
    "biotechnology",
    "nonprofit organization management",
    "dairy",
    "automotive",
    "computer games",
    "media production",
    "internet",
    "legal services",
    "arts & crafts",
    "fine art",
    "building materials",
    "government administration",
    "publishing",
    "individual & family services",
    "accounting",
    "telecommunications",
    "maritime",
    "consumer services",
    "sports",
    "music",
    "entertainment",
    "leisure, travel & tourism",
    "venture capital & private equity",
];

module.exports = {
    country_list,
    platform_list,
    revenue_list,
    tech_list,
    industry_list,
};
